# Generated by Django 4.2.5 on 2023-09-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventcalendar',
            name='answer',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
